### ISSUE TITLE
HPCWfM GUI: creating job, set min memory to 4 GB

### ISSUE THREAD

**Issue by xulman** [fiji-hpc/parallel-macro#13]
I would set default max mem (per node; the advanced settings of a new job) to something like 16 GB,
and make sure that user cannot set anything below 4 GB..

(on clusters there should be enough memory on nodes)

another question worth considering is to modify the qsub command so that scatter=xxx... I mean that i would prevent from using the same node multiple times

**Comment by xulman** [comment]
- [x] after discussion, default = 16, min = 1, shows warning when below 4
- [ ] possibly introduce a checkbox to request the scatter function

**Comment by velissarious** [comment]
I have set the default to 16 GB. When the maximum memory limit value is set to any value less than 4 GB then a warning will appear. For example:

![image](https://user-images.githubusercontent.com/23398764/168278849-d9eeaf1c-d410-4aeb-a43b-8a805acf19e7.png)

This improvement will be included in the next release.

**Comment by velissarious** [comment]
I made a new issue for the second part as it is a different new feature.
