### ISSUE TITLE
HPCWfM GUI: menu items with help

### ISSUE THREAD

**Issue by xulman** [fiji-hpc/parallel-macro#14]
that may open

- ShortGuide
- List of newly added functions
- Example folder
- Example data

Could be present direclty in Fiji menus (under HPC-ParallelTools -> Help),
and also from HPCWfM main window itself (under Help)

**Comment by velissarious** [comment]
Thank you for the feature request!

I added an `About` command which contains links to all relevant web resources.

![image](https://user-images.githubusercontent.com/23398764/168577377-0b22705a-8867-42b1-b253-6585841cba2f.png)

The user will be asked to confirm opening a link, before it opens the web browser (with a confirmation dialog).

![image](https://user-images.githubusercontent.com/23398764/168577752-96c79a2c-9f11-4ea8-bbbd-153c1ff450bf.png)

This feature will be included in the next release.
