### ISSUE TITLE
client HPCWfM checks sanity

### ISSUE THREAD

**Issue by xulman** [fiji-hpc/parallel-macro#6]
...that job dir is not the same as local working dir

**Comment by xulman** [comment]
also check and inform and error for other possible dangerous combinations... (one is subfolder of the other...)

**Comment by xulman** [comment]
WARN when starting a job and UPLOAD button wasn't pressed before....

**Comment by velissarious** [comment]
Thank you for your feedback!
This issue is now fixed. The fix will be included in the next release.
The issue was located in the `heappe-java-client` sub-project.
A warning message will be displayed and the user will be prevented from making an error.
