### ISSUE TITLE
WARN when starting a job and UPLOAD button wasn't pressed before....

### ISSUE THREAD

**Issue by xulman** [fiji-hpc/parallel-macro#8]
WARN when starting a job and UPLOAD button wasn't pressed before....

we could just forbid to re-run already finished job and offer instead a new menu item to create a new job with exactly the same settings... it would also may even make more sense... and input/output files will not be messed up.. .and we could enforce "no-running unless upload was pressed"

**Comment by velissarious** [comment]
Thank you for the feedback! :) 

I opened a new issue for the second part of this issue.

The first issue is now fixed, and the fix will be included in the next release. 

There was a bug in `hpc-workflow-manager-client` the method responsible for disabling the `Start job` context menu item was not correct, and in the case of a Jython script it did not work at all.

Now, if the job has never been uploaded, it will not be possible to start the job. Once the user uploads the job at least once, then the user will be able to start the job.
